### ISSUE TITLE
list important IPFS research problems

### ISSUE THREAD

**Issue by miyazono** [protocol/research#1]
name says it all...
and the I'll add them into the research structure

**Comment by lgierth** [comment]
Routing in large flat-namespace networks (as opposed to contemporary hierarchical networks like the internet) -- I want to write this down in more detail, just leaving this note here for now.

**Comment by miyazono** [comment]
Lars, when you write it up, can you please put it in a research-problems folder as code?  Either Markdown or LaTeX (your choice).

**Comment by windrunner0** [comment]
test,whats this?

**Comment by miyazono** [comment]
Hey @lgierth, format has changed; please add the flat-namespace routing problem as issues in this repo when you have a moment?

**Comment by windrunner0** [comment]
@miyazono  Maybe it would be true，IPFS is the future，Haha

**Comment by miyazono** [comment]
@lgierth I changed my mind, please write it up as an issue in this repo.  I'm thinking about a similar problem and I'd love to know what problem you're thinking of specifically, so I'd love to see a draft soon please!
