### ISSUE TITLE
Are there notes from the Community Research Call?

### ISSUE THREAD

**Issue by diasdavid** [protocol/research#12]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/1211152/47962388-669be900-e01c-11e8-84de-6b6065006176.png">

Perhaps not today, but it would be great to get a list of urls of projects that get discussed + recording of the session.

**Comment by miyazono** [comment]
As these were office hours, meeting notes were not taken.  Notes about potential collaborators who joined were shared with internal collaboration lists.  Attendance dropped to zero months ago, and as a result, I finally decided today to cancel the remaining meetings.  I'll restart them (likely with zoom reservations) if interest reemerges.
