### ISSUE TITLE
Tracking Academic Summer/Winter Schools

### ISSUE THREAD

**Issue by daviddias** [protocol/research#18]
The purpose of this issue is to track all the Academic Summer/Winter School programs with the goal of creating a yearly calendar that can be up to date.

Academic Summer/Winter Schools are one of the best type of events to adquire new knowledge as they typically gather all the experts in a field.

- LASER Summer School on Software Engineering https://www.laser-foundation.org/school/2019 June 1~9 2019: Elba Island, Italy    15th 
- International Super Computing Camp http://www.sc-camp.org/2019 June 10-14 2019: Madrid, Spain    
- DEBS http://www.debs2019.org/Program/DEBS_Summer_School.html June 24 2019:              
- TAROT 2019 15th International Summer School on Training And Research On Testing, University Clermont Auvergne (UCA) France, July 1-5th, 2019         
- VTSA 2019 UniGR Summer School on Verification Technology, Systems and Applications July 1-5, Belval, Luxembourg     
- Eastern European Machine Learning Summer School https://www.eeml.eu/ 1-6 July 2019                 
- Racket School 2019 The 2019 Racket Summer School of Programming Languages July 8-12, Salt Lake City        
- MLSS London, England, UK https://sites.google.com/view/mlss-2019 July 15-26, 2019 -             
- IEEE ComSoc Summer School 2019 https://www.comsoc.org/education-training/ieee-comsoc-summer-school 16th-19th July 2019 Austin, Texas     
- Deep Learning and Reinforcement Learning Summer School 2019 https://dlrlsummerschool.ca July 24 – August 2, 2019         
- Human-aligned AI Summer School http://humanaligned.ai 25 - 28 July 2019, Prague       
- DeepLearn 2019 3rd International Summer School on Deep Learning, July 22-26, 2019: Warsaw, Poland      
- MarktOberdorf Summer School 2019 International Summmerschool Marktoberdorf, "Safety and Security of Software Systems: Logics, Proofs, Applications", Jul 31-Aug 8 2019, Germany.     
- Max Planck Pre-doctoral Research School 2017: "Emerging Research Trends in Computer Science" August 6-11 2019 Saarbruecken, Germany The Cornell, Maryland, 
- MLSS Moscow, Russia  http://mlss2019.skoltech.ru August 26 - September 6, 2019         
- 14th IFIP Summer School on Privacy and Identity Management in Brugg/Windisch, Switzerland August 19-23 2019                 
- FOSAD 2019 19th International School on Foundations of Security Analysis and Design 
September August 26-30  2019, Bertinoro, Italy.         
- http://deepbayes.ru/
- http://lxmls.it.pt/2018/
- https://project.inria.fr/paiss/
- http://robotvision2019.amtc.cl/
- http://ss.cs.tsinghua.edu.cn/
- http://www.deeplearningindaba.com/
- https://nassma.um6p.ma/
- https://rlss.inria.fr/
- http://deeplearn2019.irdta.eu/
- http://visum.inesctec.pt/
- https://sites.google.com/view/seamls/home?authuser=0
- https://mlss2019.skoltech.ru/
- https://sites.google.com/view/mlss-2019
- https://www.summerschoolsineurope.eu/course/10299/subjects-in-blockchain-technology-sbt
- http://www.cds.unibe.ch/workshops/hasliberg_2018/program/
- https://blockchainsummerschool.com
- https://blockchainschool.eu/program
- https://blockchainschool.epfl.ch/

**Comment by willscott** [comment]
* Summer School on real-world crypto and privacy - Croatia - June 15–19, 2020. - https://summerschool-croatia.cs.ru.nl/2020/
* Summer School on Theory and Practice of Multi-Party Computation - Copenhagen - May 18-22 - https://events.au.dk/mpcsummerschool2020/

**Comment by daviddias** [comment]
@madavieb can you kick off a spreadsheet similar to [conferences rfp](https://docs.google.com/spreadsheets/u/1/d/1HTMKIXmix-zP2BiKYW4H4WoiGEamNymVgc8lZ466RpU/edit?ts=5c00de5c#gid=0) but for these events?

Note, we are not interested in Call for Speakers on this one, we are just interested in Name + Date + Location + Website. Thank you in advance :D

**Comment by jsoares** [comment]
- BIU Winter School on Cryptography, http://cyber.biu.ac.il/event/the-10th-biu-winter-school-on-cryptography/, February 17-20

**Comment by jsoares** [comment]
Was a spreadsheet ever created? Would be great to migrate this off the issue and into a better format.

**Comment by madavieb** [comment]
@jsoares Here's the link to the file. https://docs.google.com/spreadsheets/d/13WAcDTJS-oau_7DaLicT0dG1DdxVeKkyjXKGLkbSD_w/edit?usp=sharing

**Comment by jsoares** [comment]
Now tracked in the Research knowledge base spreadsheet (see [Handbook page](https://app.gitbook.com/@protocol-labs/s/handbook/~/drafts/-MGtI6XBB8-EX377ezdH/research/resources)). @madavieb's list (thanks!) was copied into its own tab.
