### ISSUE TITLE
Auditable Chain Of Custody

### ISSUE THREAD

**Issue by Stebalien** [protocol/research#2]
Idea: A symmetric key crypto system with two properties:

1. Keys can be split and recombined (secret sharing).
2. Keys carry a chain of custody. That is, when transferring a key from one party to another, the key will be irreversibly stamped with the identity of the receiver such that:
    1. The receiver never learns the unstamped key.
    2. The sender never learns the stamped key.
    3. The stamps survive combine/split operations.

This would allow us to implement some really nice ACL systems governed by smart contracts.

Basically, the smart contract would govern the conditions under which a key can change custody and would record all such custody transitions. All parties accepting custody of the key would have to stake some collateral against losing control of the key and, if some party discovers this key, they can report it to the smart contract to receive a portion of the collateral. The responsible party would be the last common party in both the custody chain stamped into the key and the custody chain on the blockchain (the last point at which they agree).

This gets even more interesting when one mixes in splitting/recombining of secrets. That would allow one to store secrets with untrusted independent parties and know that if they either leak a piece of the secret or collude, some party will likely report them to claim the collateral (which could be arbitrarily high).

**Comment by drewstone** [comment]
@Stebalien interesting idea. Is there any specific reason it should be a symmetric key cryptosystem? You could use a distributed key generation algorithm/[threshold signatures](https://www.iacr.org/archive/eurocrypt2000/1807/18070209-new.pdf). Changes would be signed by the honest members, etc

As far as building an ACL on top, would this manifest into only letting certain users store certain objects? If you relinquish control of the keys, you'd also have to protect against that old user still having the data right?

**Comment by silvianetobessa** [comment]
Hi all, thank you for your comments 🚀  We are now closing the issue, feel free to reopen it in the future if you want to restart the conversation on this topic.
