### ISSUE TITLE
Optical proof of work for Bitcoin

### ISSUE THREAD

**Issue by masterdezign** [protocol/research#20]
# Optical proof of work for Bitcoin

## Description

As Bitcoin gained utility and value over the last 10 years, the network incentivized billions of dollars in mining equipment and electricity expenditures. With the growth of the ecosystem, mining at home became not profitable anymore. Even the most expensive cutting edge, special-purpose mining chip doesn’t cover its energy costs unless you have direct access to very cheap electricity.

The Bitcoin network is computing about 10^20 SHA256 hashes per second which is the bulk of the computation in Bitcoin’s Proofs of Work. This is estimated to consume over 75 terawatt-hours per year, more than the electricity consumption of Austria. The consumption is growing by design as Bitcoin stores more value and in turn requires more security.

## State of the Art

New consensus mechanisms have been proposed as a means of securing cryptocurrencies whilst reducing energy cost, such as various forms of Proof of Stake and Proof of Space-Time. While many of these alternative mechanisms offer compelling guarantees, they generally require new security assumptions, which have not been stress-tested by live deployments at any adequate scale. Consequently, we still have relatively little empirical understanding of their safety. Completely changing the bitcoin paradigm is likely to introduce new unforeseen problems. We believe that the major issues discussed above can be resolved by improving rather than eliminating Bitcoin’s fundamental security layer—Proof of Work.

## Solving this Open Problem

To eliminate Bitcoin’s massive electricity consumption, a Proof of Work decoupled from energy-intensive computation is clearly needed. In the case of a Proof of Work hosting a photonic accelerator, the major cost would be the capital expense of acquiring the hardware making it a Proof of Hardware Operation. This would even make possible home mining in urban areas due to decreased electricity costs.

We propose a new Optical Proof of Work (oPoW) based on a hybrid cryptographic construction called Heavy Hash. Heavy Hash uses a proven digital hash (SHA256) to package a large amount of MAC computation into a Proof of Work puzzle. Heavy Hash can be computed on any standard digital hardware, but it becomes super-efficient only when a small digital processor is combined with a low-power photonic co-processor. An optical miner would have a small digital core flip-chipped onto a large, low-power photonic chip and bottleneck by the clock rate of the digital to analog and analog to digital converters. A cost comparable oPoW miner will have a much lower nominal hashrate (hashes/second) but each hash will correspond to proportionally more computation, hence the name Heavy Hash. 
We provide the security argument of Heavy Hash function in Section 3 https://assets.pubpub.org/xi9h9rps/01581688887859.pdf

> Why shouldn't we expect improvements to detectors, modulators, integration, or other fab modifications to result in significant hardware acceleration potential?  (both yielding development costs inaccessible to "private miners" and enabling manufacturers to easily reach 51%)

Unlike electronics, silicon photonics uses old fabrication nodes because due to the large de Broglie wavelength of photons as compared to electrons, there is no benefit to using the small feature sizes (5 nm). The result is that more old fabrication facilities can compete, not like advanced nodes
Moreover, there is lower cost of entry (masks are an order of magnitude cheaper 500k vs 5M) compared to fabrication of dedicated Bitcoin ASICs.

### Existing Conversations/Threads
https://news.ycombinator.com/item?id=21536108

Read more at https://sciencex.com/news/2020-05-powering-bitcoin-silicon-photonics-power.html
or watch Mike’s CES2020 talk https://www.youtube.com/watch?v=-URzxEjeBu4

**Comment by miyazono** [comment]
If the system bottleneck is the DAC and ADC, then wouldn't there be a clear benefit to using smaller nodes on the digital processor side (given power consumption benefits of scaling)?  If that's the case, then I'd assume that the market would treat these PoW devices like ASICs, but with an extra (optical) component.

Additionally, I think there might be a conflict between wanting to reduce the cost of entry (i.e. make mining hardware cheaper or more accessible) and reducing the energy consumption for the PoW.  If it's easier to make more mining hardware, people will just run more of them in a classic race to the bottom until it's only profitable on the margin in some locations compared to others.

**Comment by mike-powx** [comment]
Hi, that's a good insight about DACs and ADCs but they don't benefit from lower nodes as much as transistors do. In the case of BTC ASICS access, the latest or nearly latest node is a must. 

Regarding hardware cost: there is no point in making a single piece of hardware cheaper beyond some reasonable number like several thousand dollars. However, the cost of entry for new hardware manufacturers is really important. To compete in bitcoin ASIC manufacturing you need huge capital and access to the latest nodes. That's not the case for photonic chips or the digital chips that are paired with them.

**Comment by miyazono** [comment]
> To compete in bitcoin ASIC manufacturing you need huge capital and access to the latest nodes. That's not the case for photonic chips or the digital chips that are paired with them.
I was under the impression that this wasn't the case for bitcoin, and was even less true for some protocols intended to have "ASIC-resistant" proofs-of-work.  I had previously thought that, if your cost of electricity was competitive, you could buy the last generation's hardware and still profitably mine.

All that said, Protocol Labs tends to be more interested in utility tokens and useful proofs-of-work, rather than a wasted proof-of-work.  Are there uses for a token secured by an optical proof-of-work other than a store of value?

**Comment by silvianetobessa** [comment]
Hi all, thank you for your comments 🚀  We are now closing the issue, feel free to reopen it in the future if you want to restart the conversation on this topic.
