### ISSUE TITLE
Simplified low cost ventilator for developing countries

### ISSUE THREAD

**Issue by Darren-Lewis** [protocol/research#21]
# Simplified low cost ventilator for developing countries

## Problem statement
COVID-19 is here to stay, even with a vaccine (which which will take some time) the problem can't be solved overnight. Looking at the shortages of ventilators particularly in the developing world, there is an apparent need for a robust, low cost ventilator with reduced functionality tailored for treatment of COVID-19. This device must be designed safety and simply using readily available components and manufacturing processes to enable production to be scaled as quickly as possible. 

## State of the Art
Existing ventilators are of course already in production with relevant approvals however their components are scarcely available in pandemic situations and these devices will never be affordable for developing countries even once supply has caught up with demand.

### Within the broad Research Ecosystem
> How do people try to solve this problem?

A ranking of open source emergency ventilators can be found in this link: https://github.com/PubInv/covid19-vent-list

There are many great teams out there working on different open source ventilator designs, which is a great things for the following reasons:
- To increase chances chances of success (spread our bets)
- To provide users/buyers with more choice
- Component availability will restrict the deployment of a single design

### Known shortcomings of existing solutions

Many different things to consider here, more than is practical to list, but very few new emergency ventilator projects are complete and everybody still has lots to learn. To get an appreciation of the challenges involved please see the section below titled "What defines a complete solution".

### What is the impact?

The potential for saving lives is fueling these projects.

### What defines a complete successful solution?

Depending on country/region there will be different regulations to meet for an emergency ventilator for COVID treatment. UK and US examples are below:
- The MHRA rapid manufacture emergency ventilator requirements: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/879382/RMVS001_v4.pdf
- The FDA emergency ventilator submission form with standards listed: https://www.fda.gov/media/137172/download

Additionally, continuous advice must be taken from a suitability qualified medical professional, a QR-RA expert to guide the project through medical regulations and a manufacturer must be used with existing ISO13485 or equivalent quality standard accreditation.

## Safety considerations for COVID treatment:
- There is an increasing need for an adaptive ventilation mode where the device senses the patient trying to breathe before delivering air.
- PCV (Pressure Controlled Ventilatorion) mode and PRVC (Pressure Regulated Volume Control) mode are recognized as safer than VCV (Volume Control Ventilation) mode.
- It is advisable to limit maximum output to 45 cmH2O pressure and 800 ml tidal volume (advice from UK anesthetist)

### Existing Conversations/Threads

VentCon - The open source ventilator conference.
Slides found here: https://www.pubinv.org/wp-content/uploads/Vent-con-2020-Master-Program-Deck.pdf
Video recording of conference here: https://www.youtube.com/watch?v=6uwVM-0a8nY

**Comment by jsoares** [comment]
Ventilators are a little outside of our main areas of expertise but we are funding an open ventilator project in the developing world, [RespiraWorks](https://respira.works/), as well as some related testing and monitoring [modules](https://research.protocol.ai/blog/2020/announcing-our-covid-19-open-innovation-grant-awardees/).
