### ISSUE TITLE
Reusable Full Face Mask utilising UV disinfection

### ISSUE THREAD

**Issue by mikool** [protocol/research#23]
# Universal Citizen Protection Device
## Description
The UCPD is a reusable, reliable and low-cost full-face mask that provides comfortable all-day usage protecting wearers from Covid-19 virus exposure via ultraviolet disinfection. We believe there is a need for this device as existing personal protective equipment (PPE) such as surgical masks, face shields and PAPRs do not provide adequate balance between all day ergonomics, effectiveness, affordability, accessibility and availability. 
 
The UCPD team are a bunch of volunteers who believe in using their skills to help those in need during the worldwide Covid-19 pandemic. We are professionals from all walks of life who banded together through Helpful Engineering, an online open source community incubator for tackling urgent Covid-19 related issues. 
## State of the Art
The primary differentiator of the UCPD to other PPEs is the integrated concealed UV disinfection chamber. The chamber will be designed to inactivate 99% of the Covid-19 virus utilising UVC (254 nm) irradiation. UVC disinfection for water, air and surface biological contaminants is well understood and there is evidence in its effectiveness as a germicide [1 – 3]. The UCPD will be the result of utilising this established understanding to engineer a PPE that is reusable and effective.

[1] https://www.nature.com/articles/s41598-018-21058-w
[2] https://www.researchsquare.com/article/rs-25728/v1
[3] https://osf.io/wjzuq

### Within the _PROJECT_ Ecosystem
The common PPE currently in use to protect wearers from virus exposure are:
1.	Surgical Masks / Face Shields
2.	N95 respirators
3.	Powered Air Purifying Respirators (PAPRs)

Though these devices are effective to varying extents in reducing virus exposure, they each have shortcomings that the UCPD aims to resolve. Surgical masks and face shields are not certified as respiratory protective devices and research has shown that virus has been detected behind these devices [4]. N95 respirators though effective have also been observed to be poorly fitted leading to increased risk of exposure [5]. Along with that, these devices are also single use, so disposal in household trash can lead to risk of exposure.
PAPRs similarly to masks and respirators also utilises filters but are most closely related to the UCPD in terms of form. They are however prohibitively expensive.

[4] https://www.ncbi.nlm.nih.gov/pubmed/2349835
[5] https://www.ncbi.nlm.nih.gov/pubmed/10656351/
### Within the broad Research Ecosystem

To solve the problem of developing a more affordable and comfortable PPE, with wider accessibility, especially due to the shortages caused by the current pandemic, a variety of solutions have been proposed with some reaching the market. 
To meet the urgent needs of frontline health workers with high influxes of Covid-related hospitalisations, several low-tech, easily made devices such as face shields and PAPRs have been developed. A prominent example is the device developed by Maskon.org [6], that retrofits a full-face snorkel mask with a custom adapter that mates to a hospital-supplied standard viral filter. Another similar example is Bunny Science PAPR [7] that utilises a sealed plastic bag with the same filter to isolate the user.  Though these devices are effective for the healthcare fields, the robustness, ergonomics and accessibility of single use hospital filters makes it not ideally suited to other frontline occupations like manufacturing workers as well as members of the public.

On the other end of the spectrum, there are products designed more for consumer use in terms of aesthetics and ease of wear. Both the UM System [8] and A.I.R. [9] utilises the face mask / respirator form factor. UM System utilises a proprietary filter, and a UV system that inactivates the pathogen in inhaled and exhaled air whereas A.I.R utilises UV to disinfect a regular N95 mask to increase longevity and decrease risk of virus exposure. Though promising, the use of filters, both proprietary and common, can lead to issues in supply. Also, no eye protection is provided which is an entry pathway for the virus [10].

The BIOVYZR 1.0 [11] is a full-head fear that utilises filtration to form a protective barrier around the user similar to the UCPD. Though effective, this device is large, which may hinder movements in certain use cases. This device is also priced at USD$249 which may be prohibitive in parts of the world.

[6] https://maskson.org/
[7] https://bunnyscience.dozuki.com/Guide/Bunny+Science%E2%84%A2+PAPR/4
[8] https://www.um.systems/
[9] https://www.theairdevice.com/
[10] https://www.med.umich.edu/kec/pdf/coronavirus-and-your-eyes-aao.pdf
[11] https://www.vyzrtech.com/

## Solving this Open Problem
We have proposed the UCPD, which consists of a headgear and a UV disinfection chamber. The headgear will provide a seal or “bubble” around the user’s eyes, nose and mouth, with inhaled and exhaled passing through the UV disinfection chamber. The disinfection chamber utilises a UVC (254 nm) cold cathode lamp (CCL) that’s proven to be effective for inactivating biological pathogens.
 
We believe the UCPD is a better alternative to existing traditional PPEs and those within the broad research ecosystem. The UCPD will provide full head protection eliminating pathways for the virus to enter the respiratory system. It will also be designed to be easily manufactured with items that aren’t in major demand. It will also be affordable at less than $100 so that it can have widespread impact for those who need it regardless of economic status. And finally, it is aimed to be comfortable for use by frontline workers as well as members of the public who are at high risk. 
### What is the impact?

With Covid-19 cases prevalent and in some regions of the world, increasing, and vaccines up to 12 – 18 months away, the UCPD enables businesses, livelihoods and the economy to gradually ease back to normal without risks of unnecessary infections and in some regions, a potential second wave. It is intended for use by frontline workers such as health professionals, retail workers, and manufacturing workers, and as required by members of the public. We plan to provide manufacturers from all over the world with a tested open source design that can be easily manufactured at a low cost.
### What defines a complete solution?
A complete solution is a device that meets our project goals.
-	The UV chamber will need to be 99% effective in inactivating the airborne Covid-19 virus. We are preparing to test it on a reference virus at a lab.
-	The headgear needs to be comfortable, sealed, easy to put on and reusable.
-	Easy to manufacture with high interest from manufacturers.

## Current Status
We are currently in the prototyping phase of the project. We have developed the first prototype for the chamber and have undertaken UV irradiance testing in preparation for live reference virus testing with a US lab.
We are also refining the design of the headgear to increase comfort, visibility, reliability and accessibility.

https://docs.google.com/presentation/d/138o8uE1SUskLG1OIEC9REhGbiRSraX3tbcjNeDbfRRU/edit#slide=id.g848bd5cf37_0_0
https://www.helpfulengineering.org/

**Comment by jsoares** [comment]
We're closing this issue as out of scope for us. For more information on funding we provided for COVID-related efforts, check out the following links:
* [COVID grants announcement](https://research.protocol.ai/blog/2020/announcing-our-covid-19-open-innovation-grant-awardees/)
* [September 2020 update](https://research.protocol.ai/blog/2020/covid-19-open-innovation-grant-update/)
* [May 2021 update](https://research.protocol.ai/blog/2021/covid-19-open-innovation-grant-update/)
