### ISSUE TITLE
ProtocalAI Talk to San Diego Blockchain & Crypto Zoom Meetup 

### ISSUE THREAD

**Issue by LennyCastaneda** [protocol/research#24]
Would you be interested in participating in a Zoom video fireside chat to discuss ProtocalAI; (what it is, problems it solves, etc) relevant upcoming event or news and how San Diego developers can contribute to the community?

**Comment by jpgross3** [comment]
Hi @LennyCastaneda - can you send us more information about this fireside chat series in an email? You can use research [at) protocol (dot] ai. Thanks.

**Comment by jpgross3** [comment]
Conversation moved to email.
