### ISSUE TITLE
Jonathan Bootle: Zero-Knowledge Succinct Arguments with a Linear-Time Prover

### ISSUE THREAD

**Issue by anitulescu** [protocol/research#27]
### Research seminars are high level talks given by both PL and non-PL employees on topics relevant to the future of computing and internet technology. 
The series launched in September 2019. Talks can be found [here](https://www.youtube.com/watch?v=L4SJzoKHKPk&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG). If you have a suggestion on someone you would like to hear speak, please share below. If you would like to be notified of research talks in the future, please email research@protocol.ai. 

#### Speaker name
- Jonathan Bootle

#### Institution
-  IBM Research – Zurich
 
#### Suggested topic
- Zero-Knowledge Succinct Arguments with a Linear-Time Prover
 
#### Relevant paper (if any)
- https://eprint.iacr.org/2020/1527.pdf
 
#### Relevant groups at PL
- Filecoin, CryptoLab

**Comment by jpgross3** [comment]
Emailed.

**Comment by jpgross3** [comment]
Talk given, March 9, 2021.

https://www.youtube.com/watch?v=ntiJEWdGF4k&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG&index=2
