### ISSUE TITLE
Sophia Yakoubov : Secure MPC with Stateless Ephemeral Roles

### ISSUE THREAD

**Issue by ninitrava** [protocol/research#32]
### Research seminars are high level talks given by both PL and non-PL employees on topics relevant to the future of computing and internet technology. 
The series launched in September 2019. Talks can be found [here](https://www.youtube.com/watch?v=L4SJzoKHKPk&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG). If you have a suggestion on someone you would like to hear speak, please share below. If you would like to be notified of research talks in the future, please email research@protocol.ai. 

#### Speaker name
Sophia Yakoubov

#### Institution
Aarhus University
 
#### Suggested topic
YOSO: You Only Speak Once / Secure MPC with Stateless Ephemeral Roles

#### Relevant paper (if any)
 https://eprint.iacr.org/2021/210
 
#### Relevant groups at PL
CryptoNetLab, CryptoComputeLab, ResNetLab, 
anyone in general, she's a great speaker

**Comment by jpgross3** [comment]
@ninitrava thank you for this! I somehow missed it (2 months!!!) but saw it now and sent her an email. Very much appreciated.

**Comment by tjd233** [comment]
Done: https://www.youtube.com/watch?v=XKFtC6u96Ss&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG&index=2
