### ISSUE TITLE
[Hamidreza Khoshakhlagh: Balancing Privacy and Accountability in Blockchain Identity Management]

### ISSUE THREAD

**Issue by ninitrava** [protocol/research#38]
### Research seminars are high level talks given by both PL and non-PL employees on topics relevant to the future of computing and internet technology. 
The series launched in September 2019. Talks can be found [here](https://www.youtube.com/watch?v=L4SJzoKHKPk&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG). If you have a suggestion on someone you would like to hear speak, please share below. If you would like to be notified of research talks in the future, please email research@protocol.ai. 

#### Speaker name
- Hamidreza Khoshakhlagh

#### Institution
-Aarhus University
 
#### Suggested topic
- Balancing Privacy and Accountability in Blockchain Identity Management
 
#### Relevant paper (if any)
- https://eprint.iacr.org/2020/1511.pdf
 
#### Relevant groups at PL
- CryptoComputeLab, ResNetLab, CryptoNetLab, CryptoEconLab

**Comment by jpgross3** [comment]
@tjd233 I'm leaving this in your hands to reach out / schedule. Email need not be overly formal, since Anca has already spoken with him. Do be sure to include the usual info about length of talk, size of audience, etc. 🙇

**Comment by tjd233** [comment]
done: https://www.youtube.com/watch?v=totqjbvgR44&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG&index=3
