### ISSUE TITLE
[ Rosario Gennaro: A Survey of Rational Proofs]

### ISSUE THREAD

**Issue by tjd233** [protocol/research#44]
### Research seminars are high level talks given by both PL and non-PL employees on topics relevant to the future of computing and internet technology. 
The series launched in September 2019. Talks can be found [here](https://www.youtube.com/watch?v=L4SJzoKHKPk&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG). If you have a suggestion on someone you would like to hear speak, please share below. If you would like to be notified of research talks in the future, please email research@protocol.ai. 

#### Speaker name
-  Rosario Gennaro

#### Institution
- PL
 
#### Suggested topic
- A Survey of Rational Proofs
 
#### Relevant paper (if any)
-
 
#### Relevant groups at PL
-

#### Note
- Scheduled for Sept 21, 21

**Comment by jsoares** [comment]
https://www.youtube.com/watch?v=_Q-wSa2W4lw&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG&index=5
