### ISSUE TITLE
[Elena Pagnin: Count Me In! Extendability for Threshold Ring Signatures]

### ISSUE THREAD

**Issue by ninitrava** [protocol/research#51]
#### Speaker name
- Elena Pagnin
- e-mail address: elena.pagnin@eit.lth.se
- speaker knows I suggest them (you can mention me in the invitation)

#### Institution
- Lund University, Sweden
 
#### Suggested topic
- Count Me In! Extendability for Threshold Ring Signatures
- Abstract: Ring signatures enable a signer to sign a message on behalf of a group anonymously, without revealing her identity. Similarly, threshold ring signatures allow several signers to sign the same message on behalf of a group; while the combined signature reveals that some threshold t of the group members signed the message, it does not leak anything else about the signers' identities.
Anonymity is a central feature in threshold ring signature applications, such as whistleblowing, e-voting and privacy-preserving cryptocurrencies: it is often crucial for signers to remain anonymous even from their fellow signers. When the generation of a signature requires interaction, this is difficult to achieve. There exist threshold ring signatures with non-interactive signing - where signers locally produce partial signatures which can then be aggregated - but a limitation of existing threshold ring signature constructions is that all of the signers must agree on the group on whose behalf they are signing, which implicitly assumes some coordination amongst them. The need to agree on a group before generating a signature also prevents others - from outside that group - from endorsing a message by adding their signature to the statement post-factum.
We overcome this limitation by introducing extendability for ring signatures, same-message linkable ring signatures, and threshold ring signatures. Extendability allows an untrusted third party to take a signature, and extend it by enlarging the anonymity set to a larger set. In the extendable threshold ring signature, two signatures on the same message which have been extended to the same anonymity set can then be combined into one signature with a higher threshold. This enhances signers' anonymity, and enables new signers to anonymously support a statement already made by others.
 
 
#### Relevant paper (if any)
- https://eprint.iacr.org/2021/1240.pdf
- published in PKC2022
 
#### Relevant groups at PL
- CryptoNet Lab, Consensus Lab, CryptoCompute Lab, Abstraction Lab

**Comment by tjd233** [comment]
https://www.youtube.com/watch?v=UF4oy-fArU0&list=PLhuBigpl7lqu6xWpiXtbEzJQtlMH1tqoG&index=1
